version: '3'

networks:
  redis:
    driver: bridge

services:
  node:
    build: .
    volumes:
      - ".:/src/app"
    ports:
      - "5000:5000"
    networks:
      - redis
  redis_db:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - redis
